modLoader="javafml"
loaderVersion="[40,)"
license="ARR"
issueTrackerURL="https://github.com/Conquest-Reforged/ConquestReforged"

[[mods]]
modId="conquest"
version="7.0.4-forge"
displayName="Conquest Reforged"
displayURL="https://conquestreforged.com/mod"
logoFile= "conquestreforged.png"
credits='''Conquest Reforged Team'''
authors="Conquest Reforged Team"
description='''
Conquest Reforged adds hundreds of high quality textures to Minecraft for builders to use in their worlds, allowing players to delve into an endless amount of themes and building styles.
'''

# Base
[[dependencies.conquest]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.conquest]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2, 1.19)"
ordering="NONE"
side="BOTH"