modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="conquest"
displayName="${name}"
version="${version}"
logoFile="conquestreforged.png"
displayURL="https://conquestreforged.com"
issueTrackerURL="https://github.com/Conquest-Reforged/Indev"

authors="Hippokleides"

credits='''

  [Developers]
  Hippokleides

  [Artists & Modellers]
  Monsterfish
  ArtemisiaTR
  DeChoppy
  wheellee

  [Contributors]
  CreativeRealms

  With special thanks to past
  & present backers of the mod!
'''

description='''
Description:
 Conquest Reforged adds hundreds of high quality textures to Minecraft for builders to use in their worlds, allowing players to delve into an endless amount of themes and building styles.
'''