name: Java CI Stage 3

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

permissions:
  contents: write-all

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "LICENSE,build/libs/*.jar"
        tag: "latest"
        name: "Production Artifact"
        omitBody: true
